# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(help_text='AppId\u7684\u552f\u4e00\u6807\u8bc6\u540d\u79f0', max_length=100, unique=True, verbose_name='AppId\u540d\u79f0')),
                ('visible_name', models.CharField(blank=True, help_text='\u663e\u793a\u540d\u79f0', max_length=200)),
                ('life_cycle', models.SmallIntegerField(blank=True, help_text='\u751f\u547d\u5468\u671f: \u7533\u8bf7, \u521d\u59cb, \u670d\u5f79, \u8f6c\u79fb, \u5e9f\u5f03', null=True)),
                ('app_arch', models.SmallIntegerField(blank=True, help_text='\u5e94\u7528\u6846\u67b6', null=True)),
                ('thrift_port', models.PositiveIntegerField(blank=True, help_text='thrift\u7aef\u53e3\u53f7', null=True)),
                ('http_port', models.PositiveIntegerField(blank=True, help_text='HTTP\u534f\u8bae\u7aef\u53e3\u53f7', null=True)),
                ('monitor_port', models.PositiveIntegerField(blank=True, help_text='\u76d1\u63a7\u7aef\u53e3', null=True)),
                ('udp_port', models.PositiveIntegerField(blank=True, help_text='udp\u7aef\u53e3\u53f7', null=True)),
                ('dev_department', models.ForeignKey(blank=True, db_constraint=False, help_text='\u6240\u5c5e\u4ea7\u7814\u90e8\u95e8', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmc.UserDepartmentModel')),
                ('dev_user_group', models.ManyToManyField(blank=True, db_table='arch_usergroup_relate_app_dev_user_group', help_text='\u4ea7\u7814\u5c0f\u7ec4\u7ec4\u540d', null=True, to='cmc.UserGroupModel')),
                ('ops_user_group', models.ManyToManyField(blank=True, db_table='arch_usergroup_relate_app_ops_user_group', help_text='\u8fd0\u7ef4\u5c0f\u7ec4\u7ec4\u540d', null=True, to='cmc.UserGroupModel')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, help_text='\u9879\u76ee\u8d23\u4efb\u4eba', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmc.UserModel')),
            ],
            options={
                'db_table': 'arch_appid',
            },
        ),
        migrations.CreateModel(
            name='ClusterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(help_text='\u96c6\u7fa4\u540d\u79f0', max_length=100, unique=True)),
                ('visible_name', models.CharField(blank=True, help_text='\u663e\u793a\u540d\u79f0', max_length=30)),
            ],
            options={
                'db_table': 'arch_cluster',
            },
        ),
        migrations.CreateModel(
            name='ClusterTemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(help_text='\u6a21\u677f\u540d\u79f0, \u4f8b\u5982: web-proxy', max_length=100, unique=True, verbose_name='\u96c6\u7fa4\u6a21\u677f\u540d\u79f0')),
                ('description', models.TextField(help_text='\u8bf7\u586b\u5199\u76f8\u5173\u63cf\u8ff0\u4fe1\u606f, \u6700\u591a4096\u5b57\u7b26', max_length=4096, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'arch_cluster_template',
            },
        ),
        migrations.CreateModel(
            name='ClusterTemplateVersionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('version', models.PositiveIntegerField(default=0, help_text='\u7248\u672c\u53f7', verbose_name='\u7248\u672c')),
                ('changes', models.TextField(help_text='\u8bf7\u5217\u51fa\u8be6\u7ec6\u7684\u53d8\u66f4\u8bf4\u660e\u4fe1\u606f', verbose_name='\u53d8\u66f4\u63cf\u8ff0')),
                ('app_id', models.ManyToManyField(db_table='arch_cluster_template_relate_app', help_text='\u8bf7\u9009\u62e9\u9700\u5728\u96c6\u7fa4\u4e2d\u90e8\u7f72\u7684APPID\u5217\u8868', to='arch.AppIdModel', verbose_name='App ID')),
                ('config', models.ManyToManyField(blank=True, db_table='arch_cluster_template_relate_config', help_text='\u8bf7\u6dfb\u52a0\u5e94\u7528\u4e8e\u96c6\u7fa4\u7684\u914d\u7f6e', null=True, to='cmc.ConfigModel', verbose_name='\u96c6\u7fa4\u914d\u7f6e')),
            ],
            options={
                'db_table': 'arch_cluster_template_version',
            },
        ),
        migrations.CreateModel(
            name='ClusterTemplateVersionStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(help_text='\u7528\u4e8e\u6807\u8bc6\u96c6\u7fa4\u6a21\u677f\u7684\u7248\u672c\u72b6\u6001', max_length=10, unique=True, verbose_name='\u96c6\u7fa4\u6a21\u677f\u7248\u672c\u72b6\u6001')),
                ('description', models.CharField(help_text='\u8bf7\u586b\u5199\u76f8\u5173\u8bf4\u660e\u4fe1\u606f, \u6700\u591a1024\u5b57\u7b26', max_length=1024, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'arch_cluster_template_version_status',
            },
        ),
        migrations.CreateModel(
            name='EnvModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(help_text='\u8fd0\u884c\u73af\u5883\u540d\u79f0,\u4f8b\u5982: test; prod', max_length=20, unique=True)),
                ('visible_name', models.CharField(blank=True, default='', help_text='\u663e\u793a\u540d\u79f0,\u4f8b\u5982: \u6d4b\u8bd5\u73af\u5883; \u751f\u4ea7\u73af\u5883', max_length=30, null=True)),
                ('description', models.CharField(blank=True, default='', help_text='\u8be6\u7ec6\u63cf\u8ff0\u3001\u8bf4\u660e', max_length=512, null=True)),
            ],
            options={
                'db_table': 'arch_env',
            },
        ),
        migrations.CreateModel(
            name='HostGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(help_text='\u4e3b\u673a\u7ec4\u540d\u79f0', max_length=20, unique=True)),
                ('visible_name', models.CharField(blank=True, help_text='\u663e\u793a\u540d\u79f0', max_length=30)),
                ('cluster', models.ForeignKey(db_constraint=False, help_text='\u6240\u5c5e\u96c6\u7fa4', on_delete=django.db.models.deletion.SET_NULL, to='arch.ClusterModel')),
                ('env', models.ForeignKey(db_constraint=False, help_text='\u8fd0\u884c\u73af\u5883', on_delete=django.db.models.deletion.SET_NULL, to='arch.EnvModel')),
            ],
            options={
                'db_table': 'arch_hostgroup',
            },
        ),
        migrations.CreateModel(
            name='HostLifeCycleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(help_text='\u4e3b\u673a\u751f\u547d\u5468\u671f\u72b6\u6001', max_length=20, unique=True)),
                ('desc', models.CharField(blank=True, help_text='\u63cf\u8ff0', max_length=1024)),
            ],
            options={
                'db_table': 'arch_host_life_cycle',
            },
        ),
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('hostname', models.CharField(help_text='\u4e3b\u673a\u540d', max_length=50, null=True, unique=True)),
                ('box_hostname', models.CharField(help_text='\u521d\u59cb\u4e3b\u673a\u540d', max_length=50, null=True)),
                ('uuid', models.CharField(help_text='\u4e3b\u673aUUID', max_length=50, null=True, unique=True)),
                ('os_ver', models.CharField(blank=True, help_text='\u64cd\u4f5c\u7cfb\u7edf\u7248\u672c', max_length=100)),
                ('core_ver', models.CharField(blank=True, help_text='\u5185\u6838\u7248\u672c', max_length=100)),
                ('nic0_ip', models.GenericIPAddressField(blank=True, help_text='IP\u5730\u5740', null=True)),
                ('nic0_mac', models.CharField(blank=True, help_text='MAC\u5730\u5740', max_length=17)),
                ('cpu_num', models.SmallIntegerField(help_text='CPU\u6838\u6570', null=True)),
                ('mem_size', models.PositiveIntegerField(help_text='\u5185\u5b58\u5bb9\u91cf', null=True)),
                ('hd_size', models.PositiveIntegerField(help_text='\u5185\u5b58\u5bb9\u91cf', null=True)),
                ('host_type', models.CharField(blank=True, help_text='\u4e3b\u673a\u7c7b\u578b', max_length=20)),
                ('install_date', models.DateTimeField(blank=True, help_text='\u88c5\u673a\u65e5\u671f', null=True)),
                ('cluster', models.ForeignKey(db_constraint=False, help_text='\u6240\u5c5e\u96c6\u7fa4', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.ClusterModel')),
            ],
            options={
                'db_table': 'arch_host',
            },
        ),
        migrations.CreateModel(
            name='HostModelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(help_text='\u4e3b\u673a\u578b\u53f7', max_length=10, unique=True)),
                ('desc', models.CharField(blank=True, help_text='\u578b\u53f7\u63cf\u8ff0', max_length=1024)),
            ],
            options={
                'db_table': 'arch_host_model',
            },
        ),
        migrations.CreateModel(
            name='IDCModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('idc_code', models.CharField(help_text='\u673a\u623f\u552f\u4e00\u6807\u8bc6', max_length=10, unique=True)),
                ('name', models.CharField(blank=True, default='', help_text='IDC \u670d\u52a1\u5546\u7684\u7b80\u79f0', max_length=10)),
                ('desc', models.CharField(blank=True, default='', help_text='\u63cf\u8ff0', max_length=50)),
                ('address', models.CharField(blank=True, help_text='\u8be6\u7ec6\u5730\u5740', max_length=100, null=True)),
                ('contact', models.EmailField(blank=True, help_text='\u8054\u7cfb\u4eba', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='\u7535\u8bdd', max_length=15, null=True)),
                ('bandwidth_type', models.CharField(blank=True, help_text='\u5e26\u5bbd\u53ca\u7c7b\u578b', max_length=11, null=True)),
                ('remark', models.CharField(blank=True, help_text='\u5907\u6ce8', max_length=13, null=True)),
            ],
            options={
                'db_table': 'arch_idc',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(help_text='\u4ea7\u54c1\u540d\u79f0', max_length=100, unique=True)),
                ('visible_name', models.CharField(blank=True, help_text='\u663e\u793a\u540d\u79f0', max_length=30)),
                ('description', models.CharField(blank=True, help_text='\u4ea7\u54c1\u63cf\u8ff0', max_length=1024)),
                ('dev_user_group', models.ManyToManyField(blank=True, db_table='arch_usergroup_relate_product_dev_user_group', help_text='\u4ea7\u7814\u5c0f\u7ec4\u7ec4\u540d', null=True, to='cmc.UserGroupModel')),
                ('ops_user_group', models.ManyToManyField(blank=True, db_table='arch_usergroup_relate_product_ops_user_group', help_text='\u8fd0\u7ef4\u5c0f\u7ec4\u7ec4\u540d', null=True, to='cmc.UserGroupModel')),
            ],
            options={
                'db_table': 'arch_product',
            },
        ),
        migrations.CreateModel(
            name='ProjectArchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('version', models.IntegerField(default=0, help_text='\u7248\u672c\u53f7')),
                ('cluster_template', models.ManyToManyField(db_table='arch_project_arch_relate_cluster_template', help_text='\u96c6\u7fa4\u6a21\u677f', to='arch.ClusterTemplateVersionModel')),
            ],
            options={
                'db_table': 'arch_project_arch',
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(help_text='\u9879\u76ee\u540d\u79f0', max_length=100, unique=True)),
                ('visible_name', models.CharField(blank=True, help_text='\u663e\u793a\u540d\u79f0', max_length=30)),
                ('description', models.CharField(blank=True, help_text='\u9879\u76ee\u63cf\u8ff0', max_length=1024)),
                ('dev_department', models.ForeignKey(blank=True, db_constraint=False, help_text='\u6240\u5c5e\u4ea7\u7814\u90e8\u95e8', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmc.UserDepartmentModel')),
                ('dev_user_group', models.ManyToManyField(blank=True, db_table='arch_usergroup_relate_project_dev_user_group', help_text='\u4ea7\u7814\u5c0f\u7ec4\u7ec4\u540d', null=True, to='cmc.UserGroupModel')),
                ('ops_user_group', models.ManyToManyField(blank=True, db_table='arch_usergroup_relate_project_ops_user_group', help_text='\u8fd0\u7ef4\u5c0f\u7ec4\u7ec4\u540d', null=True, to='cmc.UserGroupModel')),
                ('product', models.ForeignKey(db_constraint=False, help_text='\u6240\u5c5e\u4ea7\u54c1', on_delete=django.db.models.deletion.SET_NULL, to='arch.ProductModel')),
            ],
            options={
                'db_table': 'arch_project',
            },
        ),
        migrations.CreateModel(
            name='SwimlaneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(help_text=b'\xe6\xb3\xb3\xe9\x81\x93\xe5\x90\x8d\xe7\xa7\xb0', max_length=100, unique=True)),
                ('visible_name', models.CharField(blank=True, help_text=b'\xe6\x98\xbe\xe7\xa4\xba\xe5\x90\x8d\xe7\xa7\xb0', max_length=30)),
                ('env', models.ForeignKey(db_constraint=False, help_text=b'\xe8\xbf\x90\xe8\xa1\x8c\xe7\x8e\xaf\xe5\xa2\x83ID', on_delete=django.db.models.deletion.SET_NULL, to='arch.EnvModel')),
            ],
            options={
                'db_table': 'arch_swimlane',
            },
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='swimlane',
            field=models.ManyToManyField(db_table='arch_project_relate_swimlane', help_text='\u6240\u5728\u6cf3\u9053', to='arch.SwimlaneModel'),
        ),
        migrations.AddField(
            model_name='projectarchmodel',
            name='project',
            field=models.ForeignKey(db_constraint=False, help_text='\u9879\u76ee', on_delete=django.db.models.deletion.SET_NULL, to='arch.ProjectModel'),
        ),
        migrations.AddField(
            model_name='hostmodelmodel',
            name='idc_limit',
            field=models.ManyToManyField(db_table='arch_host_model_relate_idc', help_text='\u673a\u623f\u9650\u5236, \u7528\u4e8e\u6807\u8bc6\u8be5\u578b\u53f7\u4ec5\u5728\u7279\u5b9a\u7684\u673a\u623f\u5b58\u5728', to='arch.IDCModel', verbose_name='\u6240\u5728IDC'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='conf_model',
            field=models.ForeignKey(db_constraint=False, help_text='\u4e3b\u673a\u578b\u53f7', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.HostModelModel'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='env',
            field=models.ForeignKey(db_constraint=False, help_text='\u6240\u5c5e\u73af\u5883', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.EnvModel'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='hostgroup',
            field=models.ForeignKey(db_constraint=False, help_text='\u6240\u5c5e\u4e3b\u673a\u7ec4', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.HostGroupModel'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='idc',
            field=models.ForeignKey(db_constraint=False, help_text='\u6240\u5c5e\u673a\u623f', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.IDCModel'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='ops_user_group',
            field=models.ForeignKey(db_constraint=False, help_text='\u8fd0\u7ef4\u5c0f\u7ec4', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmc.UserGroupModel'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='use_status',
            field=models.ForeignKey(db_constraint=False, help_text='\u4e3b\u673a\u751f\u547d\u5468\u671f\u72b6\u6001', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.HostLifeCycleModel'),
        ),
        migrations.AddField(
            model_name='clustertemplateversionmodel',
            name='host_model',
            field=models.ForeignKey(db_constraint=False, help_text='\u8bf7\u9009\u62e9\u96c6\u7fa4\u7684\u9ed8\u8ba4\u673a\u578b, \u53ef\u5728\u521b\u5efa\u96c6\u7fa4\u65f6\u8986\u76d6\u8fd9\u91cc\u7684\u9009\u62e9.', on_delete=django.db.models.deletion.SET_NULL, to='arch.HostModelModel', verbose_name='\u96c6\u7fa4\u9ed8\u8ba4\u673a\u578b'),
        ),
        migrations.AddField(
            model_name='clustertemplateversionmodel',
            name='status',
            field=models.ForeignKey(db_constraint=False, help_text='\u9009\u62e9\u96c6\u7fa4\u6a21\u677f\u72b6\u6001', on_delete=django.db.models.deletion.SET_NULL, to='arch.ClusterTemplateVersionStatusModel', verbose_name='\u96c6\u7fa4\u6a21\u677f\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='clustertemplateversionmodel',
            name='template',
            field=models.ForeignKey(db_constraint=False, help_text='\u96c6\u7fa4\u6a21\u677f', on_delete=django.db.models.deletion.SET_NULL, to='arch.ClusterTemplateModel'),
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='env',
            field=models.ForeignKey(db_constraint=False, help_text='\u8fd0\u884c\u73af\u5883', on_delete=django.db.models.deletion.SET_NULL, to='arch.EnvModel'),
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='host_model',
            field=models.ForeignKey(db_constraint=False, help_text='\u96c6\u7fa4\u4e3b\u673a\u673a\u578b', on_delete=django.db.models.deletion.SET_NULL, to='arch.HostModelModel'),
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='idc',
            field=models.ForeignKey(db_constraint=False, help_text='\u6240\u5728\u673a\u623f', on_delete=django.db.models.deletion.SET_NULL, to='arch.IDCModel'),
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='swimlane',
            field=models.ForeignKey(db_constraint=False, help_text='\u6240\u5c5e\u6cf3\u9053', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.SwimlaneModel'),
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='template',
            field=models.ForeignKey(db_constraint=False, help_text='\u96c6\u7fa4\u6a21\u677f', on_delete=django.db.models.deletion.SET_NULL, to='arch.ClusterTemplateModel'),
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='template_version',
            field=models.ForeignKey(db_constraint=False, help_text='\u7248\u672c\u53f7', on_delete=django.db.models.deletion.SET_NULL, to='arch.ClusterTemplateVersionModel'),
        ),
        migrations.AddField(
            model_name='appidmodel',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='\u6240\u5c5e\u4ea7\u54c1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.ProductModel'),
        ),
        migrations.AddField(
            model_name='appidmodel',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='\u6240\u5c5e\u9879\u76ee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.ProjectModel'),
        ),
        migrations.AlterUniqueTogether(
            name='clustertemplateversionmodel',
            unique_together=set([('template', 'version')]),
        ),
    ]
