# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustertemplateversionstatusmodel',
            name='name',
            field=models.CharField(help_text='\u7528\u4e8e\u6807\u8bc6\u96c6\u7fa4\u6a21\u677f\u7684\u7248\u672c\u72b6\u6001', max_length=20, unique=True, verbose_name='\u96c6\u7fa4\u6a21\u677f\u7248\u672c\u72b6\u6001'),
        ),
    ]
