# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0003_auto_20161028_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appidmodel',
            name='dev_user_group',
        ),
        migrations.RemoveField(
            model_name='appidmodel',
            name='ops_user_group',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='dev_user_group',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='ops_user_group',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='dev_user_group',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='ops_user_group',
        ),
    ]
