# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0004_auto_20161028_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='dev_department',
            field=models.ForeignKey(db_constraint=False, default='', help_text='\u6240\u5c5e\u4ea7\u7814\u90e8\u95e8', on_delete=django.db.models.deletion.SET_NULL, to='cmc.UserDepartmentModel'),
            preserve_default=False,
        ),
    ]
