# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0005_auto_20161028_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appidmodel',
            name='app_arch',
            field=models.SmallIntegerField(blank=True, help_text='\u9009\u62e9\u5e94\u7528\u67b6\u6784\u7c7b\u578b', null=True, verbose_name='\u5e94\u7528\u6846\u67b6'),
        ),
        migrations.AlterField(
            model_name='appidmodel',
            name='dev_department',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='\u9009\u62e9AppId\u7684owner\u90e8\u95e8', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmc.UserDepartmentModel', verbose_name='\u6240\u5c5e\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='appidmodel',
            name='http_port',
            field=models.PositiveIntegerField(blank=True, help_text='\u7528\u4e8eHTTP\u534f\u8bae\u901a\u4fe1\u7684\u7aef\u53e3\u53f7, \u82e5\u4e0d\u5b58\u5728, \u8bf7\u7559\u7a7a', null=True, verbose_name='HTTP\u534f\u8bae\u7aef\u53e3\u53f7'),
        ),
        migrations.AlterField(
            model_name='appidmodel',
            name='life_cycle',
            field=models.SmallIntegerField(blank=True, help_text='\u751f\u547d\u5468\u671f\u9636\u6bb5: \u7533\u8bf7, \u521d\u59cb, \u670d\u5f79, \u8f6c\u79fb, \u5e9f\u5f03', null=True, verbose_name='\u751f\u547d\u5468\u671f'),
        ),
        migrations.AlterField(
            model_name='appidmodel',
            name='monitor_port',
            field=models.PositiveIntegerField(blank=True, help_text='\u7528\u4e8e\u76d1\u63a7\u7528\u9014\u7684\u7aef\u53e3\u53f7, \u82e5\u4e0d\u5b58\u5728, \u8bf7\u7559\u7a7a', null=True, verbose_name='\u76d1\u63a7\u7aef\u53e3'),
        ),
        migrations.AlterField(
            model_name='appidmodel',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='\u9879\u76ee\u8d23\u4efb\u4eba, \u9879\u76ee\u63d0\u8bae\u3001\u7acb\u9879\u3001\u5f00\u53d1\u3001\u7ef4\u62a4\u4eba\u5458', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmc.UserModel', verbose_name='\u9879\u76eeOwner'),
        ),
        migrations.AlterField(
            model_name='appidmodel',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='\u9009\u62e9AppId\u6240\u5c5e\u7684\u4ea7\u54c1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.ProductModel', verbose_name='\u6240\u5c5e\u4ea7\u54c1'),
        ),
        migrations.AlterField(
            model_name='appidmodel',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='\u9009\u62e9AppId\u6240\u5c5e\u7684\u9879\u76ee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.ProjectModel', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='appidmodel',
            name='thrift_port',
            field=models.PositiveIntegerField(blank=True, help_text='\u7528\u4e8ethrift\u534f\u8bae\u901a\u4fe1\u7684\u7aef\u53e3\u53f7, \u82e5\u4e0d\u5b58\u5728, \u8bf7\u7559\u7a7a', null=True, verbose_name='thrift\u7aef\u53e3\u53f7'),
        ),
        migrations.AlterField(
            model_name='appidmodel',
            name='udp_port',
            field=models.PositiveIntegerField(blank=True, help_text='\u7528\u4e8eUDP\u7c7b\u578b\u7684\u7aef\u53e3\u53f7, \u82e5\u4e0d\u5b58\u5728, \u8bf7\u7559\u7a7a', null=True, verbose_name='udp\u7aef\u53e3\u53f7'),
        ),
        migrations.AlterField(
            model_name='appidmodel',
            name='visible_name',
            field=models.CharField(blank=True, help_text='\u5b8c\u6574\u7684AppID\u540d\u79f0\u3001\u4e2d\u6587\u540d\u79f0, \u7528\u4e8e\u5c55\u793a', max_length=200, verbose_name='\u663e\u793a\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, help_text='\u4ea7\u54c1\u7684\u8be6\u7ec6\u63cf\u8ff0, \u5305\u542b\u6d89\u53ca\u90e8\u95e8\u3001\u4e1a\u52a1\u529f\u80fd\u3001\u7528\u6237\u7fa4\u4f53\u3001\u6280\u672f\u67b6\u6784\u7b49', max_length=2048, verbose_name='\u4ea7\u54c1\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(help_text='\u4ea7\u54c1\u7684\u552f\u4e00\u6807\u8bc6, \u4ec5\u652f\u6301"\u82f1\u6587\u5b57\u7b26\u3001\u6570\u5b57\u3001\u4e0b\u5212\u7ebf\u548c\u8fde\u63a5\u7b26"', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='\u4ea7\u54c1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='visible_name',
            field=models.CharField(blank=True, help_text='\u5b8c\u6574\u7684\u4ea7\u54c1\u540d\u79f0\u3001\u4e2d\u6587\u540d\u79f0, \u7528\u4e8e\u5c55\u793a', max_length=1024, verbose_name='\u663e\u793a\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='description',
            field=models.CharField(blank=True, help_text='\u9879\u76ee\u7684\u8be6\u7ec6\u63cf\u8ff0, \u5305\u542b\u6d89\u53ca\u9879\u76ee\u529f\u80fd\u3001\u6280\u672f\u67b6\u6784\u7b49', max_length=1024, verbose_name='\u9879\u76ee\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='dev_department',
            field=models.ForeignKey(db_constraint=False, help_text='\u9009\u62e9\u9879\u76ee\u7684owner\u90e8\u95e8', on_delete=django.db.models.deletion.SET_NULL, to='cmc.UserDepartmentModel', verbose_name='\u6240\u5c5e\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(help_text='\u9879\u76ee\u7684\u552f\u4e00\u6807\u8bc6, \u4ec5\u652f\u6301"\u82f1\u6587\u5b57\u7b26\u3001\u6570\u5b57\u3001\u4e0b\u5212\u7ebf\u548c\u8fde\u63a5\u7b26"', max_length=100, unique=True, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='product',
            field=models.ForeignKey(db_constraint=False, help_text='\u9009\u62e9\u9879\u76ee\u6240\u5c5e\u7684\u4ea7\u54c1, \u4e00\u4e2a\u9879\u76ee\u53ea\u80fd\u6240\u5c5e\u4e00\u4e2a\u4ea7\u54c1', on_delete=django.db.models.deletion.SET_NULL, to='arch.ProductModel', verbose_name='\u6240\u5c5e\u4ea7\u54c1'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='swimlane',
            field=models.ManyToManyField(db_table='arch_project_relate_swimlane', help_text='\u9879\u76ee\u6240\u5c5e\u752c\u9053, \u9ed8\u8ba4\u7ee7\u627f\u4ea7\u54c1\u6240\u5728\u6cf3\u9053', null=True, to='arch.SwimlaneModel', verbose_name='\u6240\u5728\u6cf3\u9053'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='visible_name',
            field=models.CharField(blank=True, help_text='\u5b8c\u6574\u7684\u9879\u76ee\u540d\u79f0\u3001\u4e2d\u6587\u540d\u79f0, \u7528\u4e8e\u5c55\u793a', max_length=30, verbose_name='\u663e\u793a\u540d\u79f0'),
        ),
    ]
