# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 03:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0006_auto_20161031_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appidmodel',
            name='project',
        ),
        migrations.AddField(
            model_name='appidmodel',
            name='project',
            field=models.ManyToManyField(blank=True, db_constraint=False, db_table='arch_appid_relate_project', help_text='\u9009\u62e9AppId\u6240\u5c5e\u7684\u9879\u76ee', null=True, to='arch.ProjectModel', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(help_text='\u9879\u76ee\u7684\u552f\u4e00\u6807\u8bc6, \u4ec5\u652f\u6301"\u82f1\u6587\u5b57\u7b26\u3001\u6570\u5b57\u3001\u4e0b\u5212\u7ebf\u548c\u8fde\u63a5\u7b26"', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='swimlane',
            field=models.ManyToManyField(blank=True, db_constraint=False, db_table='arch_project_relate_swimlane', help_text='\u9879\u76ee\u6240\u5c5e\u752c\u9053, \u9ed8\u8ba4\u7ee7\u627f\u4ea7\u54c1\u6240\u5728\u6cf3\u9053', null=True, to='arch.SwimlaneModel', verbose_name='\u6240\u5728\u6cf3\u9053'),
        ),
    ]
