# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0007_auto_20161102_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustertemplateversionmodel',
            name='app_id',
            field=models.ManyToManyField(db_table='arch_cluster_template_relate_app', help_text='\u8bf7\u9009\u62e9\u9700\u5728\u96c6\u7fa4\u4e2d\u90e8\u7f72\u7684APPID\u5217\u8868', null=True, to='arch.AppIdModel', verbose_name='App ID'),
        ),
        migrations.AlterField(
            model_name='clustertemplateversionmodel',
            name='changes',
            field=models.TextField(blank=True, help_text='\u8bf7\u5217\u51fa\u8be6\u7ec6\u7684\u53d8\u66f4\u8bf4\u660e\u4fe1\u606f', verbose_name='\u53d8\u66f4\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='clustertemplateversionmodel',
            name='host_model',
            field=models.ForeignKey(db_constraint=False, help_text='\u8bf7\u9009\u62e9\u96c6\u7fa4\u7684\u9ed8\u8ba4\u673a\u578b, \u53ef\u5728\u521b\u5efa\u96c6\u7fa4\u65f6\u8986\u76d6\u8fd9\u91cc\u7684\u9009\u62e9.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.HostModelModel', verbose_name='\u96c6\u7fa4\u9ed8\u8ba4\u673a\u578b'),
        ),
    ]
