# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0009_auto_20161106_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustertemplateversionmodel',
            name='app_id',
            field=models.ManyToManyField(db_constraint=False, db_table='arch_cluster_template_relate_app', help_text='\u8bf7\u9009\u62e9\u9700\u5728\u96c6\u7fa4\u4e2d\u90e8\u7f72\u7684APPID\u5217\u8868', null=True, to='arch.AppIdModel', verbose_name='App ID'),
        ),
    ]
