# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0010_auto_20161106_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustertemplateversionmodel',
            name='config',
            field=models.ManyToManyField(blank=True, db_constraint=False, db_table='arch_cluster_template_relate_config', help_text='\u8bf7\u6dfb\u52a0\u5e94\u7528\u4e8e\u96c6\u7fa4\u7684\u914d\u7f6e', null=True, to='cmc.ConfigModel', verbose_name='\u96c6\u7fa4\u914d\u7f6e'),
        ),
    ]
