# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import omni.libs.django.field.list_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostNodeModelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='\u54c1\u724c\u540d\u79f0,\u4e3a\u82f1\u6587\u6216\u8005\u4e2d\u6587\u62fc\u97f3', max_length=10)),
                ('alias', models.CharField(help_text='\u54c1\u724c\u522b\u540d\u3001\u5168\u79f0', max_length=30)),
                ('type', models.SmallIntegerField(help_text='\u670d\u52a1\u5668\u7c7b\u578bID,\u5bf9\u5e94\u4e8eserver_tpye\u6a21\u578b\u4e2d\u7684\u4e3b\u952eID')),
                ('series', models.CharField(help_text='\u7cfb\u5217,\u4f8b\u5982\uff1aS720', max_length=20)),
                ('model', models.CharField(help_text='\u578b\u53f7', max_length=30)),
                ('cpu', models.CharField(blank=True, help_text='CPU\u578b\u53f7', max_length=20, null=True)),
                ('physical_cpu', models.SmallIntegerField(help_text='\u7269\u7406CPU\u4e2a\u6570')),
                ('cpu_core', models.SmallIntegerField(help_text='\u5355\u4e2aCPU\u6838\u5fc3\u6570')),
                ('cpu_hz', models.FloatField(blank=True, help_text='CPU\u9891\u7387,\u5355\u4f4d\u4e3a\uff1aGHZ', null=True)),
                ('memory_size', models.SmallIntegerField(help_text='\u5185\u5b58\u5927\u5c0f,\u5355\u4f4d\u4e3a\uff1aGB')),
                ('disk_num', models.SmallIntegerField(blank=True, help_text='\u6807\u914d\u78c1\u76d8\u4e2a\u6570', null=True)),
                ('disk_size', models.SmallIntegerField(blank=True, help_text='\u6807\u914d\u5355\u4e2a\u78c1\u76d8\u5927\u5c0f,\u5355\u4f4d\u4e3a\uff1aMB', null=True)),
                ('nic_model', models.CharField(help_text='\u7f51\u5361\u578b\u53f7,\u683c\u5f0f\u4e3a\uff1a\u54c1\u724c-\u578b\u53f7-\u5b50\u578b\u53f7', max_length=50)),
                ('nic_speed', models.CharField(help_text='\u7f51\u5361\u901f\u7387,\u683c\u5f0f\u4e3a\uff1a1000Mbps', max_length=10)),
                ('create_time', models.DateTimeField(help_text='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(help_text='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'host_node_model',
            },
        ),
        migrations.CreateModel(
            name='HostNodeNicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(help_text='\u7f51\u5361\u7f16\u53f7,\u7528\u4e8e\u552f\u4e00\u6807\u8bc6\u7f51\u5361,\u4e0d\u53ef\u53d8', max_length=30, unique=True)),
                ('model', models.CharField(help_text='\u7f51\u5361\u578b\u53f7,\u683c\u5f0f\u4e3a\uff1a\u54c1\u724c-\u578b\u53f7-\u5b50\u578b\u53f7', max_length=50)),
                ('is_extend', models.BooleanField(default=False, help_text='\u7f51\u5361\u662f\u5426\u4e3a\u6269\u5c55,True\u4e3a\u6269\u5c55,False\u4e3a\u8be5\u670d\u52a1\u5668\u578b\u53f7\u81ea\u5e26')),
                ('mac', models.CharField(help_text='MAC\u5730\u5740,\u683c\u5f0f\u4e3a\uff1aFFFFFFFFFFFF', max_length=12, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, help_text='\u7f51\u5361IP\u5730\u5740', null=True)),
                ('speed', models.CharField(help_text='\u7f51\u5361\u901f\u7387,\u683c\u5f0f\u4e3a\uff1a1000Mbps', max_length=10)),
                ('create_time', models.DateTimeField(help_text='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(help_text='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'host_node_nic',
            },
        ),
        migrations.CreateModel(
            name='HostNodeOSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(help_text='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b,\u53ef\u7528\u503c\u4e3a: 0->Windows\u30011->Linux\u30012->BSD\u30013->MacOSX')),
                ('name', models.CharField(help_text='\u64cd\u4f5c\u7cfb\u7edf\u53d1\u884c\u7248,\u4f8b\u5982: CentOS\u3001RHEL\u3001Windows', max_length=10)),
                ('version', models.CharField(help_text='\u4e3b\u7248\u672c\u53f7', max_length=10)),
                ('minor_version', models.CharField(blank=True, help_text='\u6b21\u7248\u672c\u53f7', max_length=10, null=True)),
                ('publisher', models.CharField(blank=True, help_text='\u53d1\u884c\u5546', max_length=100, null=True)),
                ('create_time', models.DateTimeField(help_text='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(help_text='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'host_node_os',
            },
        ),
        migrations.CreateModel(
            name='HostNodeStorageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(help_text='\u5b58\u50a8\u7f16\u53f7,\u7528\u4e8e\u552f\u4e00\u6807\u8bc6\u5b58\u50a8,\u4e0d\u53ef\u53d8', max_length=30, unique=True)),
                ('model', models.CharField(help_text='\u5b58\u50a8\u578b\u53f7,\u683c\u5f0f\u4e3a: \u54c1\u724c-\u578b\u53f7-\u5b50\u578b\u53f7', max_length=50)),
                ('is_extend', models.BooleanField(default=False, help_text='\u5b58\u50a8\u662f\u5426\u4e3a\u6269\u5c55,True\u4e3a\u6269\u5c55,Flase\u4e3a\u8be5\u670d\u52a1\u5668\u578b\u53f7\u81ea\u5e26')),
                ('type', models.CharField(help_text='\u5b58\u50a8\u7c7b\u578b,\u53ef\u7528\u503c\u4e3a: disk->\u672c\u5730\u78c1\u76d8;NFS->\u7f51\u7edc\u6587\u4ef6\u7cfb\u7edf;HDFS->hadoop\u5206\u5e03\u5f0f\u6587\u4ef6\u7cfb\u7edf;SAN->\u5b58\u50a8\u533a\u57df\u7f51\u7edc', max_length=10)),
                ('disk_size', models.IntegerField(help_text='\u78c1\u76d8\u5bb9\u91cf,\u5355\u4f4d\u4e3a\uff1aMB')),
                ('is_shared', models.BooleanField(default=False, help_text='\u8be5\u5b58\u50a8\u662f\u5426\u4e3a\u5171\u4eab\u65b9\u5f0f,\u82e5\u4e3aTrue,\u5219\u8868\u793a\u5171\u4eab,\u90a3\u4e48server\u5b57\u6bb5\u5c06\u662f\u4ee5","\u5206\u5272\u7684\u670d\u52a1\u5668\u5217\u8868')),
                ('share_name', models.CharField(blank=True, help_text='\u5171\u4eab\u5b58\u50a8\u7684\u540d\u79f0,\u7528\u4e8e\u6807\u8bc6\u4e00\u7ec4\u5171\u4eab\u5b58\u50a8', max_length=20, null=True)),
                ('mount_name', models.CharField(blank=True, help_text='\u5b58\u50a8\u6302\u8f7d\u81f3\u670d\u52a1\u5668\u540e\u7684\u8bbe\u5907\u540d\u79f0', max_length=30, null=True)),
                ('create_time', models.DateTimeField(help_text='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(help_text='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'host_node_storage',
            },
        ),
        migrations.CreateModel(
            name='HostNodeTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='\u670d\u52a1\u5668\u7c7b\u578b,\u53ef\u7528\u503c\u4e3a: 0: \u673a\u67b6\u5f0f; 1: \u5854\u5f0f; 2: \u5367\u5f0f; 3: \u4e91\u670d\u52a1\u5668; 4: \u865a\u62df\u673a', max_length=10, unique=True)),
                ('visible_name', models.CharField(blank=True, help_text='\u663e\u793a\u540d\u79f0', max_length=30, null=True)),
                ('create_time', models.DateTimeField(help_text='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(help_text='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'host_node_type',
            },
        ),
        migrations.CreateModel(
            name='ServerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(help_text='\u670d\u52a1\u5668\u8d44\u4ea7\u7f16\u53f7,\u670d\u52a1\u5668\u7684\u552f\u4e00\u6807\u793a', max_length=20, unique=True)),
                ('asset_name', models.CharField(help_text='\u8d44\u4ea7\u4e3b\u673a\u540d, \u53ef\u53d8,\u4f46\u5fc5\u987b\u552f\u4e00', max_length=20, unique=True)),
                ('sn', models.CharField(help_text='\u4e3b\u673a\u8282\u70b9SN\u7f16\u53f7,\u7528\u4e8e\u552f\u4e00\u6807\u8bc6\u670d\u52a1\u5668,\u4e0d\u53ef\u53d8', max_length=20, unique=True)),
                ('description', models.CharField(blank=True, help_text='\u8be6\u7ec6\u63cf\u8ff0', max_length=1024, null=True)),
                ('model', models.SmallIntegerField(blank=True, help_text='\u670d\u52a1\u5668\u578b\u53f7,\u4e3aserver_model\u8868ID', null=True)),
                ('nic_list', omni.libs.django.field.list_fields.ListCommaSeparatedIntegerField(blank=True, help_text='\u7f51\u5361,\u4e3aHostNodeNic\u8868ID', max_length=50, null=True)),
                ('storage_list', omni.libs.django.field.list_fields.ListCommaSeparatedIntegerField(blank=True, help_text='\u5b58\u50a8\u8bbe\u5907,\u4e3aHostNodeStorage\u8868ID', max_length=50, null=True)),
                ('os', models.SmallIntegerField(blank=True, help_text='\u64cd\u4f5c\u7cfb\u7edf,\u5bf9\u5e94\u4e8eos\u4e2d\u7684ID', null=True)),
                ('provider', models.SmallIntegerField(blank=True, help_text='\u670d\u52a1\u5668\u786c\u4ef6\u4f9b\u5e94\u5546,\u4e3aprovider\u8868\u4e3b\u952eID', null=True)),
                ('idc', models.SmallIntegerField(blank=True, help_text='IDC\u4f9b\u5e94\u5546,\u4e3aidc\u8868\u4e3b\u952eID', null=True)),
                ('rack_id', models.CharField(blank=True, help_text='\u673a\u67b6ID', max_length=20, null=True)),
                ('slot', models.CharField(blank=True, help_text='\u673a\u67b6\u4e2d\u69fd\u4f4dID', max_length=20, null=True)),
                ('status', models.SmallIntegerField(help_text='\u4e3b\u673a\u72b6\u6001,0: \u4e0b\u67b6; 1: \u5173\u673a,\u4f46\u5df2\u4e0a\u67b6; 2: \u5f00\u673a,\u6b63\u5e38; 3: \u5f00\u673a,\u672a\u6fc0\u6d3b; 4: \u672a\u77e5,\u53ef\u80fd\u5931\u53bb\u8fde\u63a5')),
                ('create_time', models.DateTimeField(help_text='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(help_text='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'asset_server',
            },
        ),
    ]
