# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0003_auto_20161028_0412'),
        ('cmc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionProductUserGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, auto_now_add=True, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_owner', models.BooleanField(default=False, help_text='\u662f\u5426Owner', verbose_name='\u662f\u5426Owner')),
                ('appid', models.ForeignKey(db_constraint=False, help_text='\u5173\u8054\u7684AppID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.AppIdModel', verbose_name='AppID')),
                ('product', models.ForeignKey(db_constraint=False, help_text='\u5173\u8054\u7684\u4ea7\u54c1', on_delete=django.db.models.deletion.SET_NULL, to='arch.ProductModel', verbose_name='\u4ea7\u54c1')),
                ('project', models.ForeignKey(db_constraint=False, help_text='\u5173\u8054\u7684\u9879\u76ee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch.ProjectModel', verbose_name='\u9879\u76ee')),
                ('usergroup', models.ForeignKey(db_constraint=False, help_text='\u5173\u8054\u7684\u7528\u6237\u7ec4', on_delete=django.db.models.deletion.SET_NULL, to='cmc.UserGroupModel', verbose_name='\u7528\u6237\u7ec4')),
            ],
            options={
                'db_table': 'user_group_permission_product',
            },
        ),
    ]
